### PR TITLE
to MD

### PR DESCRIPTION
**Pull request by utopiaio**
- i prettified the MD (i prefer md than rst)

### CODE REVIEW

**Comment by aterkik** [comment]
Looks good and I like Markdown too. However, [PyPI](https://pypi.python.org/pypi/django-chartbuilder/) expects RST and having two READMEs or converting to RST on run-time seems an overkill.

**Comment by utopiaio** [comment]
what if you have README.md and README.rst, would PyPi / GitHub be _confused_?

**Comment by aterkik** [comment]
Probably not. It's a pain to maintain two READMEs though and also potentially confusing for users. It's possible to automate this and end up with a single Markdown README (http://stackoverflow.com/a/23265673) while still submitting the RST version to PyPI. Maybe that's the way to go?

**Comment by utopiaio** [comment]
ok, just spitballing here, what if you have two branches, one for GitHub and one for PyPi, might that work?

**Pull request closed without merging**
